name: Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag/version to publish

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and push terminus Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./pkg/...

      - name: Test
        run: go test -v ./pkg/...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Extract version
        shell: bash
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/} | sed s/^v//g)"
        id: version

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
        docker build . -t $ECR_REGISTRY/terminus:${{ steps.version.outputs.tag }}
        docker push $ECR_REGISTRY/terminus:${{ steps.version.outputs.tag }}
